services:
  - type: web
    name: n8n-free
    env: docker
    repo: https://github.com/amosoltani/n8n-deploy
    plan: free
    branch: main
    envVars:
      - key: N8N_SECURE_COOKIE
        value: false
      - key: WEBHOOK_URL
        value: https://n8n-free.onrender.com
      - key: N8N_PORT
        value: 5678
